#!/bin/bash

set -e

# delombok if necessary
if git grep -q "^import lombok" '*.java'; then

  perl -pi -e 's/(\<outputDirectory\>\.\.\/)\.\.\//$1/' webgoat-lessons/pom.xml

  wget https://projectlombok.org/downloads/lombok.jar -O "/tmp/lombok.jar"
  java -jar "/tmp/lombok.jar" delombok -n --onlyChanged . -d "/tmp/delombok"
  
  find "/tmp/delombok" -name '*.java' -exec sed '/Generated by delombok/d' -i '{}' ';'
  find "/tmp/delombok" -name '*.java' -exec sed '/import lombok/d' -i '{}' ';'
  
  cp -r "/tmp/delombok/." "$(pwd)"

else
  echo "[!] No lombok code detected"
fi
